### ISSUE TITLE
Use of self in Swift

### ISSUE THREAD

**Issue by markvaldy** [hyperoslo/iOS-playbook#115]
Should we continue this discussion? We still have different thoughts about that and also we've got some issues with using of `self` in the debugger. I guess @zenangst could describe it in details.

**Comment by jgorset** [comment]
![Plotting racoon](http://25.media.tumblr.com/tumblr_lrw7ko3BsO1qelvslo1_500.gif)

**Comment by 3lvis** [comment]
Can you make this issue into a PR?

**Comment by zenangst** [comment]
I found that you cannot use `self` in the debugger, that blew my mind.

**Comment by zenangst** [comment]
I think my opinion has shifted on this, I kinda think that we should drop it. Looked at some Apple sample code which also does not use `self`.

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/iOS-playbook/pull/116 guys :)

**Comment by kostiakoval** [comment]
< I found that you cannot use self in the debugger 
any Example? @zenangst

**Comment by 3lvis** [comment]
@kostiakoval https://github.com/hyperoslo/iOS-playbook/pull/116 :)

**Comment by kostiakoval** [comment]
I mean you can't use self in LLBD? I was asking about that.

**Comment by zenangst** [comment]
At least I couldn't.
