### ISSUE TITLE
Improve: opensource.hyper.no with a list of our pods

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#125]
Would be great if we also had an admin where we could add

- Cover/logo
- Summary
- Description

We could probably automatically pull some badges from CocoaPods, TravisCI, coveralls and Github.

**Comment by jgorset** [comment]
Yep! Also number of stars we can pull from GitHub.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
