### ISSUE TITLE
Hyper-Recipe Backend Not working

### ISSUE THREAD

**Issue by PrajeetShrestha** [hyperoslo/iOS-playbook#128]
Hi, 
I am Prajeet Shrestha from Nepal. I was doing hyper recipe demo app. But the backend seems to be not working now. It says HTTP token - access denied. 
http://hyper-recipes.herokuapp.com/recipes

**Comment by jgorset** [comment]
Hey @PrajeetShrestha! We didn't really expect anyone to be using the API right now, so we updated it with authentication! You can read all about it [here](https://github.com/hyperoslo/hyper-recipes). Please note that creating new users with a seed of recipes is currently broken, though. Sorry about that!

**Comment by jgorset** [comment]
Oh, and please note that creating new users with a seed of recipes is currently broken, though, so just avoid that option for now.

**Comment by 3lvis** [comment]
Fixed on https://github.com/hyperoslo/hyper-recipes/pull/10
