### ISSUE TITLE
Swift: () -> () vs () -> Void

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#134]
>Everyone else: The Swift Programming Language ebook refers exclusively to () -> (). APIs all use () -> Void.

>I much prefer the Void typealias because it better matches return conventions in the Objective-C world.

>And now, word of Apple at devforums: “FWIW, we’ve recently decided to standardize on () -> Void (generally, () for parameters and Void for return types) across all of our documentation.”

http://ericasadun.com/2015/05/11/swift-vs-void/

**Comment by zenangst** [comment]
I prefer `() -> Void`

**Comment by kostiakoval** [comment]
Good done! + 1 to `() -> Void`

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
