### ISSUE TITLE
In PRs: Newlines and spaces should be corrected, not commented

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#142]
I've been finding myself just fixing spaces and newlines instead of making comments about them. Is this a good idea?

**Comment by kostiakoval** [comment]
+1

**Comment by RamonGilabert** [comment]
I agree!

**Comment by zenangst** [comment]
I dunno, having people point it out is a good thing, it helps you learn and do things more properly next time (hopefully). If you keep cleaning up after someone else then that person will never learn. 
I see it as overhead for the reviewer, reviewers should review, not do clean up. Don't be a maid.

**Comment by 3lvis** [comment]
@zenangst that's a good point!

**Comment by vadymmarkov** [comment]
Agree with @zenangst

**Comment by RamonGilabert** [comment]
Right, I thought @3lvis was talking about making a pull request to the pull request, then the user should merge it, or if it's merged, learn from it to make it properly the next time, for me, both ways work although easier to do a comment for the reviewed! :D

**Comment by 3lvis** [comment]
Looks like most agree in keeping it in comments. So, keeping comments then :)

**Comment by zenangst** [comment]
:heart:
