### ISSUE TITLE
Make a struct instead of extension for custom colors / fonts

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/iOS-playbook#145]
In `Objective-C` we usually made a category for `UIColor` or `UIFont` to add custom colors/fonts for keeping them in the one place. But in Swift I think it would be better to create a struct like:
```swift
struct Colors {
  static let someColor = UIColor(hex: "343434")
}
```
It looks nice and we can't get any conflicts with `UIColor` methods in the future.

**Comment by 3lvis** [comment]
I agree, if extensions are the way to go then it should look like this.

```Swift
extension UIColor {
  public func brightBlueColor -> UIColor {
    return UIColor(hex: "343434")
  }
}
```

**Comment by zenangst** [comment]
You have my vote!

**Comment by kostiakoval** [comment]
have a look on this tool. https://github.com/indragiek/swiftrsrc
It we manage to export colors from Sketch to NSColorList it would make nice code for us

**Comment by richardoti** [comment]
Agree with @vadymmarkov, that's better solution than categories, as there would no any naming conflicts and still, without using any weird prefixes (let's leave them with ObjC)

**Comment by zenangst** [comment]
@vadymmarkov mind making a pull request? :sunglasses:
