### ISSUE TITLE
Recommended pods?

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/iOS-playbook#15]

**Comment by zenangst** [comment]
https://github.com/steipete/PSTAlertController

**Comment by jgorset** [comment]
Dude, you stole my pods. AFNetworking is the only pod I know… :(

**Comment by kostiakoval** [comment]
https://github.com/jdg/MBProgressHUD

**Comment by NSElvis** [comment]
@kostiakoval what about https://github.com/TransitApp/SVProgressHUD ?

**Comment by kostiakoval** [comment]
pod 'ISO8601DateFormatter' 
https://github.com/boredzo/iso-8601-date-formatter ?

**Comment by zenangst** [comment]
https://github.com/zenangst/NSString-ZENVersions

**Comment by NSElvis** [comment]
@kostiakoval what is your main usage fro ISO8601DateFormatter?

**Comment by kostiakoval** [comment]
@NSElvis  parsing date strings into NSDate :) probably you use Property Mapping for that

**Comment by NSElvis** [comment]
@kostiakoval yeah :D (or even better :star: [Sync](https://github.com/hyperoslo/Sync) :star:)

**Comment by NSElvis** [comment]
This issue is a never ending issue. Use whatever you think it's best.
