### ISSUE TITLE
Recommended git ignore and pod ignore/accept

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#16]

**Comment by zenangst** [comment]
I think pods should be ignored, this reduces the size of the repo and makes it easier to look at pull requests. Also the change count does not make sense if you supply the pods in the repo.

**Comment by NSElvis** [comment]
This is our current one in HYPForms, I think it's pretty good.

```
# OS X
.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes

# Xcode
build/
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata
*.xccheckout
*.moved-aside
DerivedData
*.hmap
*.ipa
*.xcuserstate

# CocoaPods
Pods
```

**Comment by 3lvis** [comment]
We have an example in our pod-template. Should be enough

https://github.com/hyperoslo/pod-template
