### ISSUE TITLE
HTTP paths should be in Model

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#26]
`+ (NSString *)getPath`
`- (NSString *)deactivatePath`

**Comment by zenangst** [comment]
Should path's include arguments as well or should it just provide the base path for the models destination?

**Comment by NSElvis** [comment]
I don't know about this one, I've been thinking if we could autogenerate paths based on the Core Data models, like Rails does.

If you have a relationship user —(many)—> notes, it will generate

```
/users.json

/user/{id}/notes.json
```

**Comment by timkurvers** [comment]
Keep in mind it's `/users/:id/notes.json` not singular.

**Comment by NSElvis** [comment]
@timkurvers Thanks, fixed!

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
