### ISSUE TITLE
Preprocessed header

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/iOS-playbook#33]
Where to put #import statements, In .h, .m or .pch file?
Where to use  class forward declaration 
@class SomeClass

**Comment by kostiakoval** [comment]
Don't include import into .h, use class forward declaration instead 

**Example**
```
@class AFHTTPRequestOperation;

@interface Networking : NSObject
- (AFHTTPRequestOperation *)getData;
@end
```

**Comment by NSElvis** [comment]
>Don't include import into .h, use class forward declaration instead

@kostiakoval: Totally agree, but this only works in certain cases. Sometimes you have to import the `.h` for example when doing inheritance.

**Comment by NSElvis** [comment]
@kostiakoval: The idea is to not have a `.pch` file at all.

**Comment by kostiakoval** [comment]
@NSElvis Agree on `.pch` and they are gone on Swift, so let's move away from them

**Comment by zenangst** [comment]
Pre-complied headers have been causing problems in the past so I'm glad to see that removed.

**Comment by NSElvis** [comment]
New iOS projects and Swift projects don't contain a preprocessed header. SO I guess it's safe to kill this baby.
