### ISSUE TITLE
CoreData objects and properties naming

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/iOS-playbook#34]
Example, id fields 
``` objc
Note* note = ...
note.noteID
```

**Comment by NSElvis** [comment]
@kostiakoval: I took this approach for Kipu (https://github.com/NSElvis/Kipu#nsmanagedobject-hyppropertymapper). What do you think?

I've been thinking on using `remoteID` and `localID` but haven't wrapped my mind around it.

**Comment by zenangst** [comment]
I favor more generic naming like `remoteID` and `localID`

**Comment by kostiakoval** [comment]
:+1:  `remoteID` and `localID`

**Comment by zenangst** [comment]
Made a pull request: https://github.com/hyperoslo/iOS-playbook/pull/53
