### ISSUE TITLE
Functions that do asynchronous work should have a completion block

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#35]
Example:

I had a method `persistContext` in [DATAStack](https://github.com/NSElvis/DATAStack/blob/master/Source/DATAStack.m#L153) that did asynchronous saving.

When testing some behaviour I was calling `[dataStack persistContext]` but I was getting the wrong behaviour, then I realised that it was because of the asynchronous work on the method.

Making this method return a completion from the beginning would give me the clue that it was async.

We've experienced this also in other methods, been super clear on the async nature of your methods will make them easier to understand and test.

**Comment by zenangst** [comment]
:+1:
Without it, they become very hard / impossible to test.

**Comment by NSElvis** [comment]
**Updated with comment** :)

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
