### ISSUE TITLE
Clarify APIs with inmmutable and mutable params

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#36]
If the parameter been sent is going to be mutated then return a new instance or add it to the completion block as `updated{ParamaterName}`, otherwise is expected that the variable will not be mutated so it also could be inmmutable.

**Comment by NSElvis** [comment]
```objc
[self updateEmployee:employee completion:(NSError *error, Employee *updatedEmployee){

}]
```

**Comment by NSElvis** [comment]
```objc
// here the employee will be mutated we could easily do
// [self updateEmployee:employee usingConfiguration:configuration];
// but that would as clear/safe as:

Employee *updatedEmployee = [self updateEmployee:employee usingConfiguration:configuration];
```

**Comment by zenangst** [comment]
I think the deal is that we need to be more explicit about the mutability of the return type.
It needs to be in accordance with the API.

```objc
- (NSDictionary *)dictionary
{
    NSMutableDictionary *dictionary = [NSMutableDictionary new];
    // Here be dragons
    return [dictionary copy];
}
```
So use `copy` to be explicit indicate which mutable type the object should have when returning.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
