### ISSUE TITLE
Methods using contexts should have their NSManagedObjectContexts been passed instead of retreived from the AppDelegate

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#38]
This is mostly regarding testing, it's hard to test things that try to get everything from the AppDelegate instead of have their `dataStack` or `context` been passed.

**Comment by zenangst** [comment]
I think this should be a golden rule, this would mean that we have to rely more on convenience methods which I think is fine.

**Comment by kostiakoval** [comment]
I think it's useful for making dependency explicit and very visible (and that  is very very good)
Then you can pass it in init or setup as property

**Comment by NSElvis** [comment]
@kostiakoval: Totally! Something similar to this might be avoiding having logic in `- (void)viewDidLoad;` `-(void)viewDidAppear;` and so son.

**Comment by NSElvis** [comment]
## Core Data

Your Core Data stack should always passed to the components that need it (view controllers, methods and so on), it should never be referenced from your App Delegate or in a singleton. This helps for clarity when understanding the code and for unit testing your components.

**Comment by zenangst** [comment]
Agreed, the argument for testing the unit is key here. I think referencing the app delegate should be avoided if possible but that's another issue.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
