### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/iOS-playbook#39]
Guys, we need to perfect this, we need to agree on something and make it happen.

The most common thing that comes when this topic is discussed is:

http://semver.org

But what about a workflow of:

*Current deployed version: 1.1.0*

- You fix a bug

- You make a new version 1.1.1, you make a build ([ipa](http://upload.wikimedia.org/wikipedia/commons/d/dc/Fuller's_IPA.JPG)), upload it to Hockey/TestFlight, make a tag/release on git/GitHub then when you're ready to get some coffee and eat :cake: then...

- The QA department finds an issue with your :bug: fix

- You go back, fix the thing, your code compiles then, what the semantic versioning of your build?

We've been playing with `RC` postfix but I'm not sure if it's the best idea (I like it). Also @attila-at-hyper pointed out that HockeyApp doesn't play well with this.

So, what to do? What would be the proper version number for the release that fixes the issue with your bug fix?

cc @hyperoslo/ios @marcel-eggum @jacob-andersson (sorry if I'm forgetting someone) :bell:

**Comment by jgorset** [comment]
Pretty sure your version should be 1.1.2 if you fixed a bug in 1.1.1. Otherwise you have two versions 1.1.1 that are not the same.

**Comment by timkurvers** [comment]
:+1: on 1.1.2

**Comment by NSElvis** [comment]
@jgorset @timkurvers Then when you release to the App Store suddenly you jumped from 1.1.0 to 1.1.2?

**Comment by NSElvis** [comment]
@jgorset I guess that's the real discussion, for me it's confusing but @zenangst mentioned that the users might not care.

**Comment by timkurvers** [comment]
Being explicit about which version is in use (as opposed to cloaking/pretending to be a version) is the most important tidbit.

As @zenangst did for [singleton-rails](https://rubygems.org/gems/singleton-rails), one alternative would be to add an additional digit: 1.1.1.1

**Comment by NSElvis** [comment]
I thought we could use `-RC1`, `RC2` until we get :+1: from QA.

**Comment by attila-at-hyper** [comment]
"Skipping" a version in the App Store should be OK. In my experience users care way less about the semantics of the version number as long as they can answer the "Am I using the right version?" question.

**Comment by NSElvis** [comment]
@attila-at-hyper that's an important point, I guess nobody really cares if you are on OS X 10.10.3 and then suddenly you get a new version 10.10.8, I wouldn't go crazy or lose my mind.

**Comment by attila-at-hyper** [comment]
Exactly. You know it's newer than what you had and as it still starts with "10.10" you know it isn't a major upgrade. The rest is not so important (for end-users).

**Comment by NSElvis** [comment]
@attila-at-hyper: I've had use cases where the *user/customer* version was a few 1.X.0 lower than the one we had on develop. :(

App Store: 1.2.0
Develop: 1.3.0

So the rule is that is okay for minor, but not for mediums?

**Comment by jgorset** [comment]
I think it's major.minor.patch? Either way, I have no problem with doing it for any of them. It's just kinda weird to make a new version with new features without releasing it.

**Comment by zenangst** [comment]
In environments where you are forced to update, versioning does not really matter as much. 
At least not for the end-user, because he does not really have a choice in the matter.

I can't imagine a scenario where someone would go `Hey... where is my version 1.1.2, did you guys just cheat me out of a version... you rotten scoundrels`?

I think it's fine to just bump it by one if that a new fix is in place. Release number should be unique, if something changed, it shouldn't pretend like it didn't.

**Comment by tabishfayyaz** [comment]
I'm pretty much inline with what @jgorset said. The idea is major.minor.maintenance release. Skipping sound fine to me as well.

**Comment by NSElvis** [comment]
Thanks all :heart: !
