### ISSUE TITLE
Create own Mogenerator template to make properties without 'strong' keyword

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/iOS-playbook#40]
Right now mogenerator makes this code,
`@property (nonatomic, strong) NSNumber* number;`

In coding style we agreed to skip strong, it would be nice to skip it in model as well :)

**Comment by NSElvis** [comment]
@kostiakoval We can fork the thing and implement our changes over it, is quite abandoned.

**Comment by kostiakoval** [comment]
It's just possible to make your own template files, I think this is exactly what we need to do
http://stackoverflow.com/questions/3589247/how-do-the-mogenerator-parameters-work-which-can-i-send-via-xcode

> --template-path: The path to where the 4 .motemplate files are located. When this is not provided, it will look at all the "app support directories" (e.g. "/Library/Application Support/mogenerator/").

**Comment by NSElvis** [comment]
@kostiakoval Just saw this, interesting :)

**Comment by NSElvis** [comment]
I don't think it's a big deal since it's generated code, but we should totally improve our mogenerator templates.
