### ISSUE TITLE
access elements with [] instead of objectAtIndex:

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/iOS-playbook#41]
This is from @zenangst Comment

**Comment by zenangst** [comment]
I think it reads nicer if you use literals.

**Comment by kostiakoval** [comment]
Agree. and you can use literals for dictionaries as well. nice consistency

**Comment by NSElvis** [comment]
If there's a chance your NSDictionary could contain `NSNull` (for example when JSON is involved) then you can't use the literal notation since it could crash.

In those cases doing something like => https://github.com/NSElvis/NSDictionary-ANDYSafeValue

It's safer

**Comment by kostiakoval** [comment]
@NSElvis  nope it won't :) 
```
 NSDictionary *dic = @{@"1" : @"1",
                          @"2" : [NSNull null]};
    id o = dic[@"1"];
    id oo = dic[@"2"];
    id ooo =  dic[@"3"];
```

**Comment by kostiakoval** [comment]
The idea of that JSON safeValue that it should return `nil`, instead of `[NSNull null]`

**Comment by NSElvis** [comment]
@kostiakoval I was talking about this issues

http://stackoverflow.com/questions/16623083/how-to-handle-nsdictionary-objectforkey-json-feed-errors-crashes

https://coderwall.com/p/wfu9aw/avoid-crash-by-nsnull-objects-with-nsdictionary-verified

**Comment by kostiakoval** [comment]
I know that. But it's not NSDictionary problem. 
It's a JSON parsing + calling methods on NSNull. You can override [] method as well I hope

**Comment by NSElvis** [comment]
@kostiakoval I tried to do that, but I couldn't would be great if that worked!
