### ISSUE TITLE
iOS, the new wave

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/iOS-playbook#43]
iOS, mainly thanks to Swift, is transitioning to a whole new level. Now you hear more about Functional Programming, Reactive Programming, Immutability and so much more.

I thought I would start this issue to compile some resources that could help us to get to the next level.

Would be great if (besides the link) you added why the resource is relevant or how it could help us.

<hr>

Great introduction by [Andy Matuschak](https://twitter.com/andy_matuschak) about why this concepts are important and how they help to make better software
https://developer.apple.com/videos/wwdc/2014/
http://realm.io/news/andy-matuschak-controlling-complexity/

>Rich Hickey, the author of Clojure, is an independent software designer, consultant and application architect with over 20 years of experience in all facets of software development.

http://www.infoq.com/presentations/Are-We-There-Yet-Rich-Hickey
http://www.infoq.com/presentations/Simple-Made-Easy

Haskell and Scala are probably some of the most relevant functional languages out there, learning them is embracing *the new wave*

Learn Haskell
http://learnyouahaskell.com/

Principles of Reactive Programming
https://www.coursera.org/course/reactive

Dan Grossman’s Programming Languages Course
http://oleb.net/blog/2014/12/programming-languages-mooc/

Functional Programming Principles in Scala
https://www.coursera.org/course/progfun

**Comment by kostiakoval** [comment]
Immutability. You have probably seen this one few times few times already. 
https://www.youtube.com/watch?v=DK3vO3fUnlo

Why: It's much easier to deal with 2 immutable things than 1 mutable. 
You can pass them around and no one can change them. `Immutability = happy programer life`
+ 1 Way data flow. It would be cool to make some simple projects to show examples how it works

**Comment by RuiAAPeres** [comment]
>Value types, for example: have the following properties (3 I's) -> Interchangeable, Isolated, Inert.  

 from Andy

**Comment by NSElvis** [comment]
Made a PR with a resources section, discussion will continue there and in other issues.
