### ISSUE TITLE
Steps to make a pod

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/iOS-playbook#52]
You could look at this https://github.com/hyperoslo/pod-template

**Comment by NSElvis** [comment]
- [ ] Download https://github.com/hyperoslo/pod-template/archive/master.zip
- [ ] Move the template files that you're interested to your repo
- [ ] Replace all for "<PODNAME>"

**Comment by kostiakoval** [comment]
add How to publish pod 'pod lib lint' trunk publish

**Comment by zenangst** [comment]
- [ ] How to add owners on a pod

**Comment by NSElvis** [comment]
Oh course!

**Comment by NSElvis** [comment]
@zenangst how does the ownership will work? Should we create a `teknologi@hyper.no` account and every pod will be added also there?

**Comment by zenangst** [comment]
I guess that could work, at least that one should be a part of the owners.

**Comment by zenangst** [comment]
What do you guys think?

**Comment by NSElvis** [comment]
https://github.com/hyperoslo/iOS-playbook/pull/57

**Comment by tabishfayyaz** [comment]
how has ownership worked on the pods till now ?

**Comment by NSElvis** [comment]
For most pods is Chris and me, but if you need publish permission for any pod just raise your hand when needed

**Comment by NSElvis** [comment]
This is done, if you have another suggestion please open a separate issue.

https://github.com/hyperoslo/iOS-playbook/blob/master/COMPONENTS.md

**Comment by zenangst** [comment]
You might find this interesting - https://github.com/hyperoslo/pod-template/pull/7
