### ISSUE TITLE
Missing .gitignore and travis.yml

### ISSUE THREAD

**Issue by attila-at-hyper** [hyperoslo/iOS-playbook#82]
The `ui-component-template.zip` file you have linked from `COMPONENTS.md` doesn't seem to contain .gitignore and travis.yml files. Maybe the zip file is a snapshot of an earlier version?

**Comment by NSElvis** [comment]
@attila-at-hyper it contains those things https://github.com/hyperoslo/ui-pod-template

**Comment by NSElvis** [comment]
It links to master, maybe you have "Hidden files" enabled on OS X

**Comment by attila-at-hyper** [comment]
Yes, I've just realized that. "Hidden files" are well, hidden by default in OS X. I've downloaded & unpacked the zip then copied all files (which of course means missing the hidden file). Probably worth a mention in COMPONENTS.md.
