### ISSUE TITLE
Networking best practices

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#9]

**Comment by kostiakoval** [comment]
Networking calls should return request. This way caller can cancel request if it needs it. 
- (RequestType *)login:(NSString *)name password:(NSString *)password

**Comment by kostiakoval** [comment]
Every request should have a success and failure callback blocks
```
- (RequestType *)login:(NSString *)name success:(UserData *)data failure:(NSError *)error;
```
- It should be always Async

**Comment by NSElvis** [comment]
@kostiakoval: Interesting stuff. It's so nice to work with you again :)

**Comment by NSElvis** [comment]
I would love to get your feedback on this but this is how I think.

You don't get success, failure blocks. First reason is because is not embraced by Apple APIs and I believe consistency is key. Second because when you get a completion (success or failure) many times you want to make some operations that apply to both cases.

Example:
In a contacts app, when you update a contact you show a loading indicator then perform a PATCH request with the new contact details.

If you were to have success and failure blocks, when this get called you want to stop the loading indicator in both calls, so you duplicate code.

```objc
[ContactNetworking updateContact:contact
                         success:^{
                             [SVProgressHUD dismiss];
                         } failure:^(NSError *error) {
                             [SVProgressHUD dismiss];
                             if (error) {
                                 // present error alert
                             }
                         }];
```

If you were to have a completion block with an error parameter you would have (in your controller)

```objc
[ContactNetworking updateContact:contact
                      completion:^(NSError *error) {
                          [SVProgressHUD dismiss];
                          if (error) {
                              // present error alert
                          }
                      }];
```

That's why I prefer a completion (with error) instead of success and failure.

**Comment by NSElvis** [comment]
>Networking calls should return request. This way caller can cancel request if it needs it.

I haven't found yet a big important motive to do this. I haven't had many calls to the same resource. For `GET` requests I use [AFHTTPSessionManager-AFUniqueGET](https://github.com/NSElvis/AFHTTPSessionManager-AFUniqueGET) which makes sure that I don't have this use case.

But once I had a `GET` request that took a lot of time and was synchronous. It was a call to search for a user using an identification number, in that screen we had a cancel button, so I provided a `cancelCurrentRequest` method to my networking client, it wasn't a shared networking client, it was just a tiny networking client for the specific search.

The idea was to not keep track of the state of the networking request in the controller but keep it isolated in the networking client.

```objc
// @property (nonatomic, strong) LookupNetworking *networking;

- (void)cancelButtonAction
{
    [self.networking cancelCurrentRequest];
}
```
What do you think?

**Comment by kostiakoval** [comment]
It's never a bad thing to return a request, if you don't need it just don't use return values.
All AFNetworking calls returns requests.

I think there should be 2 type of network components (layers): 
1 - RequestMaker. Send request, holds routs and etc (it works directly with AFNetowrking API)
   - Make Requests
   - Holds Routs formats and parameters
RequestMaker is a wrapper around AFNetworking API for particular use case 
` Request *req = [RequestMaker logIn:@"name" pass:@"pass" ]`

2 - NetworkingManager. High lever controller that speaks to RequestMaker. 
  - Keep track of requests and add ability for cancelations and etc.
  - Forwarding JSON data to parsers   
 - ViewController should speak to this component

```
id<Networking> networking = [LoinNetworking networkingWith:@"name" pass:@""]
[networking login]
....
[networking cancel]
```


Smt like that. NetworkingManager shouldn't return a request to ViewController but RequestMaker does.

**Comment by kostiakoval** [comment]
About Response callbacks:
In swift I would go for i callback with a `Response` type.  
A result type would a enums with `Result` and `Error`  
In that way I would make user of that method explicitly to check for the result or error.

Let's do the same in Objc.  
```
[ContactNetworking updateContact:contact
                      completion:^(Contact *contact, NSError *error) {
              // or  completion:^(Bool updated, NSError *error) { - Nor sure if it's a good idea
                          [SVProgressHUD dismiss];
                          if (error) {
                              // present error alert
                          }
                      }];
````

Question: 
- Should result contains a Result object and Error, or can it contains only error ?
```
login...completion :(User * user, NSError *error)
logout...completion :(NSError *error) 
```

**Comment by NSElvis** [comment]
@kostiakoval What would be the advantage of having a `RequestMaker` and `NetworkingManager` over an `APIClient` with a `ContactNetworking` class? Or they are the same?

**Comment by NSElvis** [comment]
@kostiakoval 

```
APIClient — — ProductsNetworking
     |   \
     |    \
     |    UsersNetworking
     |
StoresNetworking
```

Basic `APIClient` set up, root url, any auth tokens, etc.

`UsersNetworking`, `StoresNetworking`, `ProductsNetworking`: Retrieve, create, update, delete request in a wrapper.

`UsersNetworking`: 

```objc
- (void)fetchUsers:(^)(NSError *error)completion;
- (void)createUser:(User *)user completion:(^)(NSError *error)completion;
- (void)updateUser:(User *)user completion:(^)(NSError *error)completion;
- (void)deleteUser:(User *)user completion:(^)(NSError *error)completion;
```

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
